# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailarchives', '0004_resend_rate_limit'),
    ]

    operations = [
        migrations.RunSQL(
            """
ALTER TABLE messages ADD COLUMN rawtxt bytea NOT NULL;
ALTER TABLE messages ADD COLUMN fti tsvector NOT NULL;
ALTER TABLE attachments ADD COLUMN attachment bytea NOT NULL;
CREATE TABLE loaderrors(
   id SERIAL NOT NULL PRIMARY KEY,
   listid int NOT NULL,
   dat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   msgid text NOT NULL,
   srctype text NOT NULL,
   src text NOT NULL,
   err text NOT NULL
);
CREATE SEQUENCE threadid_seq;
CREATE TABLE list_months(
   listid int NOT NULL REFERENCES lists(listid),
   year int NOT NULL,
   month int NOT NULL,
   CONSTRAINT list_months_pk PRIMARY KEY (listid, year, month)
);
CREATE TABLE list_threads(
   threadid int NOT NULL, /* comes from threadid_seq */
   listid int NOT NULL REFERENCES lists(listid),
   CONSTRAINT pg_list_threads PRIMARY KEY (threadid, listid)
);
CREATE INDEX list_threads_listid_idx ON list_threads(listid);
CREATE TABLE unresolved_messages(
   message int NOT NULL REFERENCES messages,
   priority int NOT NULL,
   msgid text NOT NULL,
   CONSTRAINT unresolved_messages_pkey PRIMARY KEY (message, priority)
);
CREATE UNIQUE INDEX idx_unresolved_msgid_message ON unresolved_messages(msgid, message);

/* A couple of convenience views that exclude the content fields. */
CREATE VIEW messages_meta AS
   SELECT
      id,
      parentid,
      threadid,
      _from,
      _to,
      cc,
      subject,
      date,
      has_attachment,
      hiddenstatus,
      messageid
   FROM messages;

CREATE VIEW attachments_meta AS
   SELECT
      id,
      message,
      filename,
      contenttype
   FROM attachments;

INSERT INTO listgroups (groupid, groupname, sortkey) VALUES (1, 'Developer lists', 1)
    ON CONFLICT (groupid) DO NOTHING;

INSERT INTO lists (listid, listname, shortdesc, description, active, groupid, subscriber_access)
   VALUES (1, 'pgsql-hackers', 'pgsql-hackers', -- implicit concatentation below
      'The PostgreSQL developers team lives here. '
      'Discussion of current development issues, problems and bugs, and proposed new features. '
      'If your question cannot be answered by people in the other lists, '
      'and it is likely that only a developer will know the answer, you may re-post your question in this list. '
      'You must try elsewhere first!', True, 1, True)
      ON CONFLICT (listid) DO NOTHING;

CREATE TEXT SEARCH CONFIGURATION pg (COPY=pg_catalog.english);

/*
CREATE TEXT SEARCH DICTIONARY english_ispell (
   TEMPLATE = ispell,
   DictFile = english,
   AffFile = english,
   StopWords = english
);
CREATE TEXT SEARCH DICTIONARY pg_dict (
   TEMPLATE = synonym,
   SYNONYMS = pg_dict
);
CREATE TEXT SEARCH DICTIONARY pg_stop (
   TEMPLATE = simple,
   StopWords = pg_dict
);
*/
ALTER TEXT SEARCH CONFIGURATION pg
   ALTER MAPPING FOR asciiword, asciihword, hword_asciipart,
                     word, hword, hword_part
    WITH english_stem;

ALTER TEXT SEARCH CONFIGURATION pg
   DROP MAPPING FOR email, url, url_path, sfloat, float;

CREATE FUNCTION messages_fti_trigger_func() RETURNS trigger AS $$
BEGIN
   NEW.fti = setweight(to_tsvector('public.pg', coalesce(new.subject, '')), 'A') ||
             setweight(to_tsvector('public.pg', coalesce(new.bodytxt, '')), 'D');
   RETURN NEW;
END
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER messages_fti_trigger
 BEFORE INSERT OR UPDATE OF subject, bodytxt ON  messages
 FOR EACH ROW EXECUTE PROCEDURE messages_fti_trigger_func();

CREATE INDEX messages_fti_idx ON messages USING gin(fti);

            """,
        ),

    ]
