# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailarchives', '0004_resend_rate_limit'),
    ]

    operations = [
        migrations.RunSQL(
            """
ALTER TABLE messages ADD COLUMN rawtxt bytea NOT NULL;
ALTER TABLE attachments ADD COLUMN attachment bytea NOT NULL;

CREATE TABLE loaderrors(
   id SERIAL NOT NULL PRIMARY KEY,
   listid int NOT NULL,
   dat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
   msgid text NOT NULL,
   srctype text NOT NULL,
   src text NOT NULL,
   err text NOT NULL
);

CREATE SEQUENCE threadid_seq;

CREATE TABLE list_months(
   listid int NOT NULL REFERENCES lists(listid),
   year int NOT NULL,
   month int NOT NULL,
   CONSTRAINT list_months_pk PRIMARY KEY (listid, year, month)
);

CREATE TABLE list_threads(
   threadid int NOT NULL, /* comes from threadid_seq */
   listid int NOT NULL REFERENCES lists(listid),
   CONSTRAINT pg_list_threads PRIMARY KEY (threadid, listid)
);

CREATE INDEX list_threads_listid_idx ON list_threads(listid);

CREATE TABLE unresolved_messages(
   message int NOT NULL REFERENCES messages,
   priority int NOT NULL,
   msgid text NOT NULL,
   CONSTRAINT unresolved_messages_pkey PRIMARY KEY (message, priority)
);

CREATE UNIQUE INDEX idx_unresolved_msgid_message ON unresolved_messages(msgid, message);

create view messages_meta as select id, parentid, threadid, _from, _to, cc, subject, date, has_attachment, hiddenstatus, messageid from messages;

create view attachments_meta as select id, message, filename, contenttype from attachments;

INSERT INTO listgroups (groupid, groupname, sortkey) VALUES (1, 'Developer lists', 1);
INSERT INTO lists (listid, listname, shortdesc, description, active, groupid, subscriber_access) VALUES (1, 'pgsql-hackers', 'pgsql-hackers', 'The PostgreSQL developers team lives here. Discussion of current development issues, problems and bugs, and proposed new features. If your question cannot be answered by people in the other lists, and it is likely that only a developer will know the answer, you may re-post your question in this list. You must try elsewhere first!', True, 1, True);

            """,
        ),
        
    ]
