# Generated by Django 4.2.20 on 2025-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailarchives', '0005_sync_with_loader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parentid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
