# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 19:02
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('mailarchives', '0006_alter_message_parentid'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE FUNCTION is_patch(att attachments) RETURNS boolean LANGUAGE sql IMMUTABLE STRICT
    RETURN (att).filename ~ '\.(diff|diff\.gz|patch|patch\.gz|tar\.gz|tgz|tar\.bz2|zip)$';
;
            """,
            reverse_sql="""
DROP FUNCTION is_patch(att attachments);
            """,
        ),
    ]
